services:
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    container_name: MinIO-Aloper
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./data:/data  # Thư mục local để chứa file
      # - ./config:/root/.minio  # Lưu trữ cấu hình
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin@123
      - MINIO_DEFAULT_BUCKETS=files
    networks:
      - aloper-prod_default

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong@Passw0rd
    ports:
      - '1433:1433'
    networks:
      - aloper-prod_default
    
networks:
  aloper-prod_default:
